In [56]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Text Classification using Machine Learning Models

### 📝 Instructions: Trump Tweet Sentiment Classification

1. **Load the Dataset**  
   Load the dataset named `"trump_tweet_sentiment_analysis.csv"` using `pandas`. Ensure the dataset contains at least two columns: `"text"` and `"label"`.

2. **Text Cleaning and Tokenization**  
   Apply a text preprocessing pipeline to the `"text"` column. This should include:
   - Lowercasing the text  
   - Removing URLs, mentions, punctuation, and special characters  
   - Removing stopwords  
   - Tokenization (optional: stemming or lemmatization)
   - "Complete the above function"

3. **Train-Test Split**  
   Split the cleaned and tokenized dataset into **training** and **testing** sets using `train_test_split` from `sklearn.model_selection`.

4. **TF-IDF Vectorization**  
   Import and use the `TfidfVectorizer` from `sklearn.feature_extraction.text` to transform the training and testing texts into numerical feature vectors.

5. **Model Training and Evaluation**  
   Import **Logistic Regression** (or any machine learning model of your choice) from `sklearn.linear_model`. Train it on the TF-IDF-embedded training data, then evaluate it using the test set.  
   - Print the **classification report** using `classification_report` from `sklearn.metrics`.

In [57]:
import pandas as pd
import numpy as np

In [58]:
df = pd.read_csv("/content/drive/MyDrive/Artificial Intelligence /Week - 8 - Getting Started with NLP - Text Pre - processing and Text Representations/trum_tweet_sentiment_analysis.csv")

**Ensuring Dataset contains Text and Label**

In [59]:
df.head()

                                                text  Sentiment
0  RT @JohnLeguizamo: #trump not draining swamp b...          0
1  ICYMI: Hackers Rig FM Radio Stations To Play A...          0
2  Trump protests: LGBTQ rally in New York https:...          1
3  "Hi I'm Piers Morgan. David Beckham is awful b...          0
4  RT @GlennFranco68: Tech Firm Suing BuzzFeed fo...          0

In [60]:
df_text=df[['text']]   # creates a series

In [61]:
df_text.dropna()   #It deletes rows that contain empty values.

                                                      text
0        RT @JohnLeguizamo: #trump not draining swamp b...
1        ICYMI: Hackers Rig FM Radio Stations To Play A...
2        Trump protests: LGBTQ rally in New York https:...
3        "Hi I'm Piers Morgan. David Beckham is awful b...
4        RT @GlennFranco68: Tech Firm Suing BuzzFeed fo...
...                                                    ...
1850118  Everytime im like 'How the fuck I follow Melan...
1850119  RT @imgur: The Trump Handshake. https://t.co/R...
1850120  "Greenspan warns Trump's policies risk inflati...
1850121  RT @FasinatingLogic: We must also #INVESTIGATE...
1850122  RT @imgur: The Trump Handshake. https://t.co/R...

[1850123 rows x 1 columns]

## Helper Function for Text Cleaning:

Implement a Helper Function as per Text Preprocessing Notebook and Complete the following pipeline.

Removing URLs

In [62]:
import re
def remove_urls(text):
  """
  This function will try to remove URL present in out dataset and replace it with space using regex library.
  Input Args:
  text: strings of text that may contain URLs.
  Output Args:
  text: URLs replaces with text
  """
  url_pattern = re.compile(r'https?://\S+|www\.\S+')
  return url_pattern.sub(r'', text)

In [63]:
text_no_url = df_text["text"].apply(remove_urls)

In [64]:
text_no_url

0          RT @JohnLeguizamo: #trump not draining swamp b...
1          ICYMI: Hackers Rig FM Radio Stations To Play A...
2          Trump protests: LGBTQ rally in New York  by #B...
3          "Hi I'm Piers Morgan. David Beckham is awful b...
4          RT @GlennFranco68: Tech Firm Suing BuzzFeed fo...
                                 ...
1850118    Everytime im like 'How the fuck I follow Melan...
1850119                    RT @imgur: The Trump Handshake.
1850120    "Greenspan warns Trump's policies risk inflati...
1850121    RT @FasinatingLogic: We must also #INVESTIGATE...
1850122                    RT @imgur: The Trump Handshake.
Name: text, Length: 1850123, dtype: object

Remove Emojis

In [65]:
def remove_emoji(string):
  """
  This function will replace the emoji in string with whitespace
  """
  emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
  return emoji_pattern.sub(r' ', string)

In [66]:
def removeunwanted_characters(document):
  """
  This function will remove all the unwanted characters from the input dataset.
  Input Args:
  documet: A text data to be cleaned.
  Return:
  A cleaned document.
  """
  # remove user mentions
  document = re.sub("@[A-Za-z0-9_]+"," ", document)
  # remove hashtags
  document = re.sub("#[A-Za-z0-9_]+","", document)
  # remove punctuation
  document = re.sub("[^0-9A-Za-z ]", "" , document)
  #remove emojis
  document = remove_emoji(document)
  # remove double spaces
  document = document.replace('  ',"")
  return document.strip()       # Removes extra spaces from the start and end of a string.

In [67]:
text_removed_unwanted = df_text["text"].apply(removeunwanted_characters)
text_removed_unwanted

0          RTnot draining swamp but our taxpayer dollars ...
1          ICYMI Hackers Rig FM Radio Stations To Play An...
2          Trump protests LGBTQ rally in New York httpstc...
3          Hi Im Piers Morgan David Beckham is awful but ...
4          RT Tech Firm Suing BuzzFeed for Publishing Unv...
                                 ...
1850118    Everytime im like How the fuck I follow Melani...
1850119    RT The Trump Handshake httpstcoRI78itAbC4 http...
1850120    Greenspan warns Trumps policies risk inflation...
1850121    RT We must also s who voted NOT to allow the r...
1850122    RT The Trump Handshake httpstcoRI78itAbC4 http...
Name: text, Length: 1850123, dtype: object

In [68]:
import nltk #the main NLP library (toolbox)
nltk.download('punkt_tab')  #punkt provides the rules/data needed to split text properly
from nltk import word_tokenize #worker (function that uses the rules of punkt)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [79]:
from nltk.tokenize import RegexpTokenizer

def remove_punct(text):
  """
  This function removes the punctutations present in our text data.
  Input Args:
  text: text data.
  Returns:
  text: cleaned text.
  """
  return re.sub(r"[^\w\s]", "", text)

Remove Stop Words

In [70]:
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stop_words = set(stopwords.words('english'))
custom_stopwords = ['@', 'RT']
stop_words.update(custom_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [71]:
def remove_stopwords(text_tokens):
  """
  This function removes all the stopwords present in out text tokens.
  Input Args:
  text_tokens: tokenize input of our datasets.
  Returns:
  result_tokens: list of token without stopword.
  """

  result_tokens = []
  for token in text_tokens:
    if token not in stop_words:
       result_tokens.append(token)
  return result_tokens

Lemmatization

In [72]:
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize,pos_tag
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

def lemmatization(token_text):
  """
  This function performs the lemmatization operations as explained above.
  Input Args:
  token_text: list of tokens.
  Returns:
  lemmatized_tokens: list of lemmatized tokens.
  """
  lemma_tokens = []
  wordnet = WordNetLemmatizer()
  lemmatized_tokens = [wordnet.lemmatize(token, pos = 'v') for token in token_text]

  return lemmatized_tokens

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [73]:
from nltk.stem import PorterStemmer

def stemming(text):
  """
  This function performs stemming operations.
  Input Args:
  token_text: list of tokenize text.
  Returns:
  stemm_tokes: list of stemmed tokens.
  """
  porter = PorterStemmer()
  stemm_tokens = []
  for word in text:
    stemm_tokens.append(porter.stem(word))
  return stemm_tokens

Lower Order

In [74]:
def lower_order(text):
  """
  This function converts all the text in input text to lower order.
  Input Args:
  token_text : input text.
  Returns:
  small_order_text : text converted to small/lower order.
  """
  small_order_text = text.lower()
  return small_order_text

# Build a Text Cleaning Pipeline

In [75]:
def text_cleaning_pipeline(dataset, rule = "lemmatize"):
  """
  This...
  """
  # Convert the input to small/lower order.
  data = lower_order(dataset)
  # Remove URLs
  data = remove_urls(dataset)
  # Remove emojis
  data = remove_emoji(dataset)
  # Remove all other unwanted characters.
  data = removeunwanted_characters(dataset)
  # Remove punctuation
  data = remove_punct(data)
  # Create tokens.
  tokens = data.split()
  # Remove stopwords:
  tokens = [word for word in tokens if word not in stop_words]

  wordnet = WordNetLemmatizer()
  porter = PorterStemmer()

  if rule == "lemmatize":
    tokens = [wordnet.lemmatize(word, pos='v') for word in tokens]
  elif rule == "stem":
    tokens = [porter.stem(word) for word in tokens]
  else:
    print("Pick between lemmatize or stem")


  return " ".join(tokens)

In [80]:
df['clean_text'] = df['text'].apply(text_cleaning_pipeline)

df[['text', 'clean_text', 'Sentiment']].head()

,text,clean_text,Sentiment
0,RT @JohnLeguizamo: #trump not draining swamp b...,RTnot drain swamp taxpayer dollars trip advert...,0
1,ICYMI: Hackers Rig FM Radio Stations To Play A...,ICYMI Hackers Rig FM Radio Stations To Play An...,0
2,Trump protests: LGBTQ rally in New York https:...,Trump protest LGBTQ rally New York httpstcoLfH...,1
3,"""Hi I'm Piers Morgan. David Beckham is awful b...",Hi Im Piers Morgan David Beckham awful Donald ...,0
4,RT @GlennFranco68: Tech Firm Suing BuzzFeed fo...,Tech Firm Suing BuzzFeed Publishing Unverified...,0

In [81]:
from sklearn.model_selection import train_test_split

X = df['clean_text']
y = df['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [83]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [84]:
from sklearn.metrics import classification_report, accuracy_score

y_pred = model.predict(X_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9160624282143098
              precision    recall  f1-score   support

           0       0.93      0.95      0.94    248842
           1       0.89      0.84      0.87    121183

    accuracy                           0.92    370025
   macro avg       0.91      0.90      0.90    370025
weighted avg       0.92      0.92      0.92    370025